apiVersion: v1
kind: Service
metadata:
  name: teamspeak-mysql
  labels:
    app: teamspeak
spec:
  ports:
    - port: 3306
  selector:
    app: teamspeak
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak-mysql
  labels:
    app: teamspeak
spec:
  selector:
    matchLabels:
      app: teamspeak
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: teamspeak
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        resources:
          requests:
            cpu: "200m"
            memory: "256M"
          limits:
            cpu: "1000m"
            memory: "2014M"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
            path: /mnt/md0/databases/teamspeak