apiVersion: v1
kind: Service
metadata:
  name: teamspeak
  annotations:
    metallb.universe.tf/address-pool: "teamspeak"
  labels:
    app: teamspeak
spec:
  ports:
    - port: 10011
      protocol: TCP
      targetPort: 10011
      name: query
    - port: 30033
      protocol: TCP
      targetPort: 30033
      name: files
    - port: 10080
      protocol: TCP
      targetPort: 10080
      name: webquery
  selector:
    app: teamspeak
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: teamspeak-server
  annotations:
    metallb.universe.tf/address-pool: "teamspeak-server"
  labels:
    app: teamspeak
spec:
  ports:
    - port: 9987
      protocol: UDP
      targetPort: 9987
      name: connection
  selector:
    app: teamspeak
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamspeak
  labels:
    app: teamspeak
spec:
  selector:
    matchLabels:
      app: teamspeak
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: teamspeak
        tier: frontend
    spec:
      containers:
      - image: teamspeak
        name: teamspeak
        resources:
          requests:
            cpu: "200m"
            memory: "256M"
          limits:
            cpu: "1000m"
            memory: "2014M"
        env:
#        - name: TS3SERVER_QUERY_PROTOCOLS
#          value: "ssh,raw,http,https,tcp,telnet"
        - name: TS3SERVER_DB_PLUGIN
          value: ts3db_mariadb
        - name: TS3SERVER_DB_SQLCREATEPATH
          value: create_mariadb
        - name: TS3SERVER_DB_USER
          value: root
        - name: TS3SERVER_DB_NAME
          value: teamspeak
        - name:  TS3SERVER_DB_WAITUNTILREADY
          value: "30"
        - name:  TS3SERVER_LICENSE
          value: accept
        - name: TS3SERVER_DB_HOST
          value: teamspeak-mysql
        - name: TS3SERVER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 9987
          protocol: UDP
          name: teamspeak
        - containerPort: 10080
          protocol: TCP
          name: webquery
        - containerPort: 10011
          protocol: TCP
          name: teamspeakquery
        - containerPort: 30033
          protocol: TCP
          name: teamspeakfile
        volumeMounts:
        - name: teamspeak-persistent-storage
          mountPath: /var/ts3server
        - name: entrypoint
          mountPath: /opt/ts3server/entrypoint.sh
      volumes:
      - name: teamspeak-persistent-storage
        hostPath:
            path: /mnt/md0/teamspeak/
      - name: entrypoint
        hostPath:
            path: /mnt/md0/teamspeak/entrypoint.sh