apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mc
spec:
  replicas: 1
  selector:
    matchLabels:
      role: mc
  template:  
    metadata:
      labels:
        role: mc
    spec:
      containers:
      - image:  itzg/minecraft-server
        name:  minecraft
        resources:
          requests:
            cpu: "200m"
            memory: "1024M"
          limits:
            cpu: "4000m"
            memory: "8192M"
        livenessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 300
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 40
          timeoutSeconds: 10
          periodSeconds: 20
        env:
        - name:  WORLD
          value:  "/data/world"
        - name: EXEC_DIRECTLY
          value: "true"
        - name: TZ
          value: "Europe/Madrid"
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "1.17.1"
        - name: TYPE
          value: "PAPER"
        ports:
        - containerPort:  25565
          name:  mc
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          hostPath:
            path: /mnt/md0/minecraft_survival
---
kind: Service
apiVersion: v1
metadata:
  name:  minecraft
  annotations:
    metallb.universe.tf/address-pool: "games"
    external-dns.alpha.kubernetes.io/hostname: mc.blueclouds.es
    external-dns.alpha.kubernetes.io/target: public
spec:
  selector:
    role:  mc
  type:  LoadBalancer
  ports:
  - name:  minecraft
    port:  25565
    targetPort:  25565